server {
  listen 80;
  listen [::]:80;
  server_name wreckloud.com www.wreckloud.com;

  root /srv/lycanclaw/frontend/current;
  index index.html;
  error_page 404 /404.html;

  location = /404.html {
    internal;
  }

  location / {
    try_files $uri $uri.html $uri/ =404;
  }
}
